# This is a basic workflow to help you get started with Actions

name: Fred

on:
  push:
    branches: [ "new_master", "workflow-tinkering" ]
  pull_request:
    branches: [ "new_master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check for new entries in timeline/timeline_entries/
    runs-on: ubuntu-latest
    outputs: 
      newEntries: ${{ steps.checking.outputs.entries }}
    steps:
      - name: Checkout the repo with fetch-depth = 2
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Extract the number of new ./timeline_entries/ files in HEAD commit
        id: checking      
        run: |
          echo "# git log -1 --oneline --name-status"
          git log -1 --oneline --name-status
          echo "# git diff HEAD^ --name-only | grep 'timeline_entries/' | wc -l"
          NUMBER_OF_NEW_ENTRIES=$(git diff HEAD^ --name-only  | grep 'timeline_entries/' | wc -l)
          echo "entries=$NUMBER_OF_NEW_ENTRIES" >> "$GITHUB_OUTPUT"
          echo "Number of new entries: [$NUMBER_OF_NEW_ENTRIES]"
  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.newEntries > 0 }}
    steps:
      - name: Checkout the new commit
        uses: actions/checkout@v4
      - name: Set up Node on the runner
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies and build the React app
        working-directory: timeline/react-app
        run: |
          echo "Node version: [$(node --version)]"
          npm ci
          echo "RUNNING: npm run prebuild"
          npm run prebuild
          echo "...DONE"
          echo "RUNNING: npm run build"
          npm run build
          echo "...DONE"
          echo "# stat ./timeline/pages/index.html"
          stat ../../pages/index.html
      - name: Upload static Pages file index.html as artifact
        # DOC: https://github.com/marketplace/actions/upload-github-pages-artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./timeline/pages
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
