# This is a basic workflow to help you get started with Actions

name: Fred

on:
  push:
    branches: [ "new_master", "workflow-tinkering" ]
  pull_request:
    branches: [ "new_master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkfortimelineentries:
    name: Check for new entries in timeline_entries/, abort workflow if none
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          echo "# git log -1 --oneline --name-status"
          git log -1 --oneline --name-status
          echo "# git diff HEAD^ --name-only | grep 'timeline_entries/' | wc -l"
          NUMBER_OF_NEW_ENTRIES=$(git diff HEAD^ --name-only  | grep 'timeline_entries/' | wc -l)
          echo "NUMBER_OF_NEW_ENTRIES=$NUMBER_OF_NEW_ENTRIES" >> "$GITHUB_ENV"
          echo "Number of new entries: [$NUMBER_OF_NEW_ENTRIES]"
  buildtimeline:
    if: ${{ github.env.NUMBER_OF_NEW_ENTRIES > 0 }}
    runs-on: ubuntu-latest
    needs: checkfortimelineentries
    steps:
      - name: Checkout the new commit
        uses: actions/checkout@v4
      - name: Run the timeline.py script to build a new timeline.html
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: |
          echo "running timeline script..."
          echo "Python version: [$(python --version)]"
          echo "...script completed"
          echo "# stat ./timeline.html"
          stat ./timeline.html
      - name: Upload static Pages file timeline.html as artifact
        # DOC: https://github.com/marketplace/actions/upload-github-pages-artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./timeline.html
  deploytimeline:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: buildtimeline
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


